# app/src/main/resources/application.yml

spring:
  application:
    name: multiagent-platform

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

resilience:
  retry:
    maxAttempts: 5
    initialInterval: 1000   # ms
    multiplier: 2.0
  circuitbreaker:
    failureRateThreshold: 60.0
    waitDurationInOpenState: 60000      # ms
    slidingWindowSize: 50
    permittedNumberOfCallsInHalfOpenState: 5